### ISSUE TITLE
TrabalhoFelipeMeireles

### ISSUE THREAD

**Issue by ghost** [professornivaldo/auladetestes#45]
GITHUB
Ano de lançamento = 2008
Quem é o proprietário/criador = Microsoft
Qual a principal característica de cada uma = A oportunidade de aprender com programadores
e programadoras mais experientes que você, especializado nas mesmas ou em diferentes áreas. 

GITLAB
Ano de lançamento = 2011
Quem é o proprietário/criador = GitLab Inc, Dmitriy Zaporozhets
Qual a principal característica de cada uma = Oferece ferramentas essenciais de gerenciamento de projetos para 
monitorar e controlar os membros da sua equipe. Não é apenas um sistema de controle de versão para o código fonte do seu software.

BITBUCKET
Ano de lançamento = 2008
Quem é o proprietário/criador = Atlassian
Qual a principal característica de cada uma = O ambiente é favorável para o compartilhamento de dados, criação e implantação de 
códigos e automatização de testes no melhor conceito de cloud 
o Bitbucket Cloud, por exemplo, está hospedado nos servidores da Atlassian e pode ser acessado por meio de um URL mas também 
permite hospedagem local, em infraestruturas on-premises — o Bitbucket 
Server, que suporta soluções como o Bamboo e automatiza todos os processos com licença infinita.

VISUAL STUDIO TEAMS SERVICES
Ano de lançamento = 2005
Quem é o proprietário/criador = Microsoft
Qual a principal característica de cada uma = Microsoft Visual Studio é um ambiente de desenvolvimento integrado (IDE) da Microsoft
para desenvolvimento de software especialmente dedicado ao .NET, Framework e às linguagens Visual Basic (VB),C, C++, C# (C Sharp) e F# (F Sharp). 
Também é um produto de desenvolvimento na área web, usando a plataforma do ASP.NET,como websites, aplicativos web, serviços web e aplicativos móveis.

**Comment by professornivaldo** [comment]
Está no lugar errado
